In [38]:
import numpy as np

In [39]:
list = [1, 2, 3, 4, 5]
print(list)
print(type(list))

[1, 2, 3, 4, 5]
<class 'list'>


In [40]:
numpy_list = np.array(list)
print(numpy_list)
print(type(numpy_list))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [41]:
array2D = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]
print(array2D)
print(type(array2D))

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]
<class 'list'>


In [42]:
numpy_array2D = np.array(array2D)
print(numpy_array2D)
print(type(numpy_array2D))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
<class 'numpy.ndarray'>


In [43]:
np.arange(0,25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [44]:
np.arange(0,25,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [45]:
np.arange(0,10).reshape(2,5)
np.arange(0,10).reshape(1,10)
#Product of rows and columns must equal num elements in the array

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [46]:
np.ones(25, dtype=int).reshape(5,5)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [47]:
print(np.eye(3))
#Creates identity matrix of size n x n
print(np.eye(5, dtype=int))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [48]:
print(np.random.rand(5)) #random values from 0 to 1
print(np.random.randn(5)) #random values from the normal distribution
print(np.random.randint(0,100,2)) #prints random ints in range low to high (low, high, size)

[0.83249836 0.7408659  0.27471953 0.02268023 0.8207865 ]
[ 0.51166764 -0.13567275  0.14823225 -0.74460135  0.19147401]
[ 0 79]


In [49]:
A = np.random.randint(0, 100, 20).reshape(4, 5)
print(A)
print(f"The smallest value: {A.min()}, and is located at position: {A.argmin()}")
print(f"The largest value: {A.max()}, and is located at position: {A.argmax()}")
print(f"The current shape of A is {A.shape}")
#You can put variables inside print strings!!!!!!!

[[97 88 82 93 87]
 [34 62  8 21 58]
 [37 61 65 66 26]
 [58 79 70 98  2]]
The smallest value: 2, and is located at position: 19
The largest value: 98, and is located at position: 18
The current shape of A is (4, 5)


In [50]:
A = np.arange(1, 16)
B = np.arange(1, 30, 2)
C = np.arange(0, 4).reshape(2, 2)
D = np.arange(0, 4).reshape(2, 2)
E = np.arange(1, 16).reshape(3, 5)
F = np.arange(11)
print(f'A: {A}')
print(f'B: {B}')
print('C:')
print(C)
print('D:')
print(D)
print('E:')
print(E)
print(f'F: {F}')

A: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
B: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]
C:
[[0 1]
 [2 3]]
D:
[[0 1]
 [2 3]]
E:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
F: [ 0  1  2  3  4  5  6  7  8  9 10]


In [51]:
print(A+B) #Adds items elementwise
print(A+5) #Adds 5 to each item in the array
print(A*B) #Multiplies arrays elementwise
print(A/B)
print(B/A)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44]
[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[  1   6  15  28  45  66  91 120 153 190 231 276 325 378 435]
[1.         0.66666667 0.6        0.57142857 0.55555556 0.54545455
 0.53846154 0.53333333 0.52941176 0.52631579 0.52380952 0.52173913
 0.52       0.51851852 0.51724138]
[1.         1.5        1.66666667 1.75       1.8        1.83333333
 1.85714286 1.875      1.88888889 1.9        1.90909091 1.91666667
 1.92307692 1.92857143 1.93333333]


In [52]:
print(np.matmul(C, D)) #perfoms matrix multiplication
print(np.sqrt(E))
print(np.log(E))
#these universal functions are cool because they work on all the elements of the array without needing a for loop

[[ 2  3]
 [ 6 11]]
[[1.         1.41421356 1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712 3.         3.16227766]
 [3.31662479 3.46410162 3.60555128 3.74165739 3.87298335]]
[[0.         0.69314718 1.09861229 1.38629436 1.60943791]
 [1.79175947 1.94591015 2.07944154 2.19722458 2.30258509]
 [2.39789527 2.48490665 2.56494936 2.63905733 2.7080502 ]]


In [53]:
print(np.where(F%2==0, -1, F*100))

[ -1 100  -1 300  -1 500  -1 700  -1 900  -1]


# Indexing

In [54]:
A = np.arange(15)
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [59]:
print(f'A[0]: {A[0]}')
print(f'A[5]: {A[5]}')
print(f'A[14]: {A[14]}')
print(A[1:6]) #This is another really cool feature you can easily slice an array
A[0:5] = 10 #Can change any values along the slice
print(A)

A[0]: 10
A[5]: 5
A[14]: 14
[10 10  3  4  5]
[10 10 10 10 10  5  6  7  8  9 10 11 12 13 14]


In [61]:
B = np.arange(50).reshape(5, 10) #5 rows 10 columns 2D array
print(B)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [66]:
print(f'0th row and 2nd col in B: {B[0, 2]}')
print(f'3rd row and 3rd col in B: {B[3, 3]}')
print(f'4th row and 2nd col in B: {B[4, 2]}')
#Indexing 2D array is the same as C++
print(B[0:2, 3:5]) #Really cool you can also index slices of a 2D array in a single line
B[0:2, 3:5] = 0
print(B)

0th row and 2nd col in B: 2
3rd row and 3rd col in B: 33
4th row and 2nd col in B: 42
[[0 0]
 [0 0]]
[[ 0  1  2  0  0  5  6  7  8  9]
 [10 11 12  0  0 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


## Boolean array indexing

A really cool feature of NumPy is that we can index arrays using comparison operators. This Lets us modify or select only elements meeting some condition. To demonstrate this, lets first see what is returned when we try to use comparison operators with our arrays

In [67]:
C = np.arange(50).reshape(10, 5)
print(C)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


In [68]:
print(C%2 == 0) #Prints a 2D boolean array cooresponding to the truth values at each index against the condition

[[ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]
 [False  True False  True False]]


In [71]:
print((C%2 == 0).sum()) #Sums up all the truth values from the condition
print(C[C%2 == 0]) #This will only give you the indexes that match the condition

25
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]
